- name: Launch node-exporter
  become: true
  docker_container:
    name: node-exporter
    image: quay.io/prometheus/node-exporter:latest
    restart_policy: always
    command: '--path.rootfs=/host'
    network_mode: host
    pid_mode: host
    volumes:
      - '/:/host:ro,rslave'
