- name: Install topgrade
  become: '{{ install_sudo }}'
  yay:
    name: topgrade
  when: ansible_distribution == 'Archlinux'

- name: Install topgrade
  homebrew:
    name: topgrade
  when: ansible_distribution == 'MacOSX'

- name: Install topgrade
  package:
    name: topgrade
  when: ansible_distribution != 'MacOSX' and ansible_distribution != 'MacOSX'
