- hosts: all
  roles:
    - role: gantsign.visual-studio-code-extensions
      users:
        - username: "{{ ansible_facts['user_id'] }}"
          visual_studio_code_extensions:
            - dendron.dendron-paste-image
            - bmewburn.vscode-intelephense-client
          # visual_studio_code_extensions_absent:
          #   - seanmcbreen.Spell
