- name: install zeal
  become: '{{ install_sudo }}'
  yay:
    name: zeal
  when: ansible_distribution != 'MacOSX'

- name: install dash
  homebrew_cask:
    name: dash
  when: ansible_distribution == 'MacOSX'
