- name: Install fail2ban
  become: true
  package:
    name: fail2ban
    state: latest

- name: make slack notification action
  become: true
  template:
    src: slack-notify.conf
    dest: /etc/fail2ban/action.d/slack-notify.conf

- name: apply jail.local
  become: true
  copy:
    src: jail.local
    dest: /etc/fail2ban/jail.local

- name: enable fail2ban
  become: true
  systemd:
    name: fail2ban
    enabled: true

- name: restart fail2ban
  become: true
  systemd:
    name: fail2ban
    state: restarted
