- name: install aws cli
  become: true
  package:
    name: aws-cli
  when: ansible_distribution != 'MacOSX'

- name: install aws cli
  homebrew:
    name: awscli
  when: ansible_distribution == 'MacOSX'

- name: install aws eb cli
  pip:
    name: awsebcli
  when: ansible_distribution != 'MacOSX'

- name: install aws eb cli
  homebrew:
    name: aws-elasticbeanstalk
  when: ansible_distribution == 'MacOSX'
