- name: install zoom
  become: '{{ install_sudo }}'
  yay:
    name: zoom
  when: ansible_distribution != 'MacOSX'

- name: install zoom
  homebrew_cask:
    name: zoom
  when: ansible_distribution == 'MacOSX'
