- name: Install systemd-timesyncd
  become: true
  package:
    name: systemd-timesyncd
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Enable and start NTP synchronisation
  become: true
  systemd:
    name: systemd-timesyncd.service
    enabled: true
    state: started

- name: Set timezone and hardware clock
  become: true
  timezone:
    hwclock: '{{ time.hwclock }}'
    name: '{{ time.timezone }}'
