- name: Launch watchtower
  become: true
  docker_container:
    name: watchtower
    image: containrrr/watchtower
    restart_policy: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env:
      WATCHTOWER_NOTIFICATIONS: "slack"
      WATCHTOWER_NOTIFICATION_SLACK_CHANNEL: "{{ slack.channels.updates.name | default('updates') }}"
      WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: "{{ slack.update_hook }}"
      WATCHTOWER_NOTIFICATION_SLACK_ICON_EMOJI: ":whale:"
      WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER: "{{ ansible_hostname }}"
      WATCHTOWER_SCHEDULE: "0 0 */2 * * *"
      WATCHTOWER_ROLLING_RESTART: "true"
      TZ: "{{ time.timezone | default('Europe/Riga') }}"
  ignore_errors: true
