#!/usr/bin/env bash

# https://wiki.archlinux.org/index.php/Pacman#Upgrading_packages
# https://wiki.archlinux.org/index.php/System_maintenance#Upgrading_the_system


# Upgrade AUR (yay) via running git install script again.
# ------------------------------------------------------------------------------
#       https://github.com/Jguer/yay/issues/1087#issuecomment-545585765
# TODO: only remove and reinstall if newer yay package exists.

topgrade
