# https://lopes.id/hardening-arch-linux/
#

# 0 - hardened
- name: Archlinux hardened
  become: true
  package:
    name:
      - linux-hardened
      - linux-hardened-headers

- name: boot linux hardened
  become: true
  ansible.builtin.lineinfile:
    path: /boot/loader/entries/arch.conf
    regexp: '^linux /vmlinuz'
    line: 'linux /vmlinuz-linux-hardened'

- name: boot initrd haredened
  become: true
  ansible.builtin.lineinfile:
    path: /boot/loader/entries/arch.conf
    regexp: '^initrd /initramfs'
    line: 'initrd /initramfs-linux-hardened.img'

# 1 -- disable core dumps

- name: coredump.conf storage
  become: true
  ansible.builtin.lineinfile:
    path: /etc/systemd/coredump.conf
    regexp: '^#Storage='
    line: 'Storage=none'

- name: coredump.conf processsizemax
  become: true
  ansible.builtin.lineinfile:
    path: /etc/systemd/coredump.conf
    regexp: '^#ProcessSizeMax='
    line: 'ProcessSizeMax=0'

- name: copy core dump configuration sysctl
  become: true
  copy:
    src: 50-coredump.conf
    dest: /etc/sysctl.d/50-coredump.conf

- name: create coredump.conf.d
  become: true
  file:
    path: /etc/systemd/coredump.conf.d
    state: directory

- name: copy core dump configuration systemd
  become: true
  copy:
    src: coredump.conf
    dest: /etc/systemd/coredump.conf.d/custom.conf

- name: ulimit -c 0
  become: true
  ansible.builtin.lineinfile:
    path: /etc/profile
    regexp: '^ulimit'
    line: 'ulimit -c 0'

- name: security/limits.conf
  become: true
  ansible.builtin.lineinfile:
    path: /etc/security/limits.conf
    regexp: '^#\*               soft    core            0'
    line: '*               soft    core            0'

# sysctl -p /etc/sysctl.d/50-coredump.conf

# 2 -- PAM

- name: Copy pam passwd
  become: true
  copy:
    src: passwd
    dest: /etc/pam.d/passwd

# 3 -- Login defs

- name: Apply login.defs rounds
  become: true
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: '^SHA_CRYPT_MIN_ROUNDS='
    line: 'SHA_CRYPT_MIN_ROUNDS={{ SHA_ROUNDS }}'

# 4 - arch audit

- name: Install arch audit
  become: '{{ install_sudo }}'
  package:
    name: arch-audit

# 5 - etc/issue
- name: Replace issue
  become: true
  replace:
    path: /etc/issue
    regexp: 'Arch Linux'
    replace: 'I like trains!'

# 6 - permissions
- name: set file permissions
  become: true
  file:
    dest: '{{ item.path }}'
    mode: '{{ item.mode }}'
  ignore_errors: yes
  with_items:
    - path: /etc/cron.deny
      mode: 600
    - path: /etc/group
      mode: 644
    - path: /etc/group-
      mode: 644
    - path: /etc/issue
      mode: 644
    - path: /etc/passwd
      mode: 644
    - path: /etc/passwd-
      mode: 644
    - path: /etc/ssh/sshd_config
      mode: 600
    - path: /etc/cron.d
      mode: 700
    - path: /etc/cron.daily
      mode: 644
    - path: /etc/cron.hourly
      mode: 644
    - path: /etc/cron.weekly
      mode: 644
    - path: /etc/cron.monthly
      mode: 644

# 7 - auditd

- name: Copy audit rules
  become: true
  copy:
    src: audit.rules
    dest: /etc/audit/audit.rules

- name: Install auditd
  become: '{{ install_sudo }}'
  package:
    name:
     - audit
     - sysstat

- name: enable auditd
  become: true
  systemd:
    name: auditd
    enabled: true
    state: started

- name: enable sysstat
  become: true
  systemd:
    name: sysstat
    enabled: true
    state: started

# 8 - file integrity

# - name: Install file integrity
#   become: '{{ install_sudo }}'
#   yay:
#     name: tripwire-git
#   notify: init tripwire
